// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sdawgworckavzusnmjvi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNkYXdnd29yY2thdnp1c25tanZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE0MjA0OTksImV4cCI6MjA3Njk5NjQ5OX0.7MFI80v4CABfhYUZ3p0w3bgEuLQN89QpfEWbVLeRubE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});